server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 100M;

    add_header X-Content-Type-Options "nosniff" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass          127.0.0.1:9000;
        fastcgi_index          index.php;
        include                fastcgi_params;
        fastcgi_param          SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param          PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout   300;
        fastcgi_buffer_size    16k;
        fastcgi_buffers        4 16k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
